In [4]:
import numpy as np 
import pandas as pd 
import os 
import subprocess

In [42]:
result = subprocess.run(['wsl', 'hmmscan', '-h'], stdout=subprocess.PIPE, text=True)

In [43]:
from stride import pdb_to_fasta
pdb_to_fasta('./stride/AF-P0ABF1-F1.pdb', './data/fastas/AF-P0ABF1-F1.fasta')

In [44]:
# amino acid order: A, R, N, D, C, Q, E, G, H, I, L, K, M, F, P, S, T, W, Y, V
aa_order = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']
blosum62_background = np.array([0.078, 0.051, 0.041, 0.052, 0.024, 0.034, 0.059, 0.083, 0.025, 0.062, 0.092, 0.056, 0.024, 0.044, 0.043, 0.059, 0.055, 0.014, 0.034, 0.072])

In [45]:
len('------------MKALVYTPSLPRFFGARLLGKRFPR---KLLPLRLAE------VPLPEREGFLRVRVRLSGVCGS--DL---A-------------L-----------------L-------Y--------G-------K------SPPS-------------------I---------------------------------------S----P---F-----------------FS--F------------PAVLGHE-----I----L--------G------E----M------------EGSLVAVNPLLACADRG-----L----P-------P-----C-------PR-------------CQEGEEGLCQNVA---E-----GPLAPGML----GYNRDLPGGWGEWVLARP---E---RL-----H-------P---I--P-PGVP----------------------------EERAVFAEPLAVVLRGLNKLKPW---P---E----E----------V-----L----V------------LGMGTIGLLAVRLL-----R------------A--------L-------GY----TG------RLLAVAKYPHQA--E--------------RAKAFGADGVYGS------------A-----------K------------E----------A-----------L--------------------------------L---------A--------R---ARRYRYLLFEGHR----GGYEAVVEASGSGRGFREALALAREGGKV----LL------L---GA----------PGL-E-V---------------------------VD-L-SP-----------------FW-----F----K----E----V--A--L-----------WG--S--Y--TY-------------TREEFRE--AVGLLPELEGLESLVGG----------------------VYPL-------EAWPEALVAKG-----KALFRPKG----------------------------')

1084

In [46]:
from Bio import AlignIO

In [47]:
alignment = AlignIO.read('./data/Pfam/output_alignment.fasta', 'fasta')

In [48]:
sequ = alignment[-1].seq

In [49]:
sequstr = np.array(sequ)

In [50]:
prot_seq = alignment[-1].seq
print(np.where(np.array(prot_seq) != '-')[0])

[  12   13   14   15   16   17   18   19   20   21   22   23   24   25
   26   27   28   29   30   31   32   33   34   35   36   40   41   42
   43   44   45   46   47   48   55   56   57   58   59   60   61   62
   63   64   65   66   67   68   69   70   71   72   73   74   75   76
   79   80   84   98  116  124  133  141  148  149  150  151  171  211
  216  220  238  239  242  255  256  257  258  259  260  261  267  272
  281  288  293  306  307  308  309  310  311  312  313  314  315  316
  317  318  319  320  321  322  328  333  341  347  355  356  370  371
  372  373  374  375  376  377  378  379  380  381  382  386  392  393
  394  395  396  397  398  399  404  405  406  407  408  409  410  411
  412  413  414  415  416  417  418  419  420  421  425  429  430  436
  444  448  451  453  454  455  456  485  486  487  488  489  490  491
  492  493  494  495  496  497  498  499  500  501  502  503  504  505
  506  507  511  515  520  531  537  542  555  556  557  558  559  560
  561 

In [51]:
testarr = sequstr != '-'

In [52]:
np.where(testarr)[0]

array([  12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   40,   41,   42,   43,   44,   45,   46,   47,
         48,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   79,   80,   84,   98,  116,  124,  133,  141,  148,  149,
        150,  151,  171,  211,  216,  220,  238,  239,  242,  255,  256,
        257,  258,  259,  260,  261,  267,  272,  281,  288,  293,  306,
        307,  308,  309,  310,  311,  312,  313,  314,  315,  316,  317,
        318,  319,  320,  321,  322,  328,  333,  341,  347,  355,  356,
        370,  371,  372,  373,  374,  375,  376,  377,  378,  379,  380,
        381,  382,  386,  392,  393,  394,  395,  396,  397,  398,  399,
        404,  405,  406,  407,  408,  409,  410,  411,  412,  413,  414,
        415,  416,  417,  418,  419,  420,  421,  4

In [53]:
columns = np.where(testarr)[0]

In [54]:
testcol = alignment[:, 933]

In [55]:
print(np.sum(np.array(list(testcol)) == 'A'))

5716


In [56]:
for aa in aa_order:
    print(f'{aa}:{np.sum(np.array(list(testcol)) == aa)}' if np.sum(np.array(list(testcol)) == aa) > 0 else '', end=' ')

A:5716 R:17247 N:5444 D:7705 C:605 Q:4708 E:4261 G:1268 H:2513 I:1503 L:1595 K:9268 M:780 F:656 P:36 S:21572 T:35293 W:177 Y:599 V:5925 

In [57]:
for x,y in enumerate(columns):
    print(x, y)

0 12
1 13
2 14
3 15
4 16
5 17
6 18
7 19
8 20
9 21
10 22
11 23
12 24
13 25
14 26
15 27
16 28
17 29
18 30
19 31
20 32
21 33
22 34
23 35
24 36
25 40
26 41
27 42
28 43
29 44
30 45
31 46
32 47
33 48
34 55
35 56
36 57
37 58
38 59
39 60
40 61
41 62
42 63
43 64
44 65
45 66
46 67
47 68
48 69
49 70
50 71
51 72
52 73
53 74
54 75
55 76
56 79
57 80
58 84
59 98
60 116
61 124
62 133
63 141
64 148
65 149
66 150
67 151
68 171
69 211
70 216
71 220
72 238
73 239
74 242
75 255
76 256
77 257
78 258
79 259
80 260
81 261
82 267
83 272
84 281
85 288
86 293
87 306
88 307
89 308
90 309
91 310
92 311
93 312
94 313
95 314
96 315
97 316
98 317
99 318
100 319
101 320
102 321
103 322
104 328
105 333
106 341
107 347
108 355
109 356
110 370
111 371
112 372
113 373
114 374
115 375
116 376
117 377
118 378
119 379
120 380
121 381
122 382
123 386
124 392
125 393
126 394
127 395
128 396
129 397
130 398
131 399
132 404
133 405
134 406
135 407
136 408
137 409
138 410
139 411
140 412
141 413
142 414
143 415
144 416
145 417
14

In [58]:
columns_sub = columns[:10].astype(object)

In [59]:
test = np.array(list(testcol))[np.array(list(testcol)) != '-']
test

array(['T', 'S', 'T', ..., 'S', 'R', 'A'], dtype='<U1')

In [60]:
np.array(list(alignment[:,12]))[np.array(list(alignment[:,12])) != '-']

array(['a', 'a', 'a', 'l', 'M'], dtype='<U1')

In [61]:
col_no_gaps = np.char.upper(np.array(list(alignment[:, 12]))[np.array(list(alignment[:, 12])) != '-'])

In [62]:
type(alignment[:,12])

str

In [63]:
type(columns_sub.astype(object)[0])

int

In [64]:
columns_sub

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21], dtype=object)

In [65]:
#textresult = result_hmmscan.stdout

NameError: name 'result_hmmscan' is not defined

In [26]:
columns = columns.astype(object)

In [27]:
for n_col, col in enumerate(columns_sub):
    print(n_col, col)
    col_no_gaps = np.char.upper(np.array(list(alignment[:, col]))[np.array(list(alignment[:, col])) != '-'])
    for aa in aa_order:
        print(f'{aa} : {np.sum(col_no_gaps == aa)/len(col_no_gaps)}')

0 12
A : 0.6
R : 0.0
N : 0.0
D : 0.0
C : 0.0
Q : 0.0
E : 0.0
G : 0.0
H : 0.0
I : 0.0
L : 0.2
K : 0.0
M : 0.2
F : 0.0
P : 0.0
S : 0.0
T : 0.0
W : 0.0
Y : 0.0
V : 0.0
1 13
A : 0.2
R : 0.0
N : 0.0
D : 0.0
C : 0.0
Q : 0.0
E : 0.0
G : 0.0
H : 0.0
I : 0.0
L : 0.0
K : 0.4
M : 0.0
F : 0.0
P : 0.0
S : 0.0
T : 0.4
W : 0.0
Y : 0.0
V : 0.0
2 14
A : 0.4
R : 0.2
N : 0.0
D : 0.0
C : 0.0
Q : 0.0
E : 0.0
G : 0.0
H : 0.0
I : 0.0
L : 0.2
K : 0.0
M : 0.0
F : 0.0
P : 0.0
S : 0.0
T : 0.2
W : 0.0
Y : 0.0
V : 0.0
3 15
A : 0.0
R : 0.0
N : 0.0
D : 0.0
C : 0.0
Q : 0.0
E : 0.0
G : 0.0
H : 0.0
I : 0.0
L : 0.4
K : 0.0
M : 0.0
F : 0.0
P : 0.2
S : 0.2
T : 0.0
W : 0.0
Y : 0.0
V : 0.2
4 16
A : 0.2857142857142857
R : 0.0
N : 0.0
D : 0.0
C : 0.0
Q : 0.0
E : 0.0
G : 0.0
H : 0.0
I : 0.0
L : 0.0
K : 0.14285714285714285
M : 0.0
F : 0.2857142857142857
P : 0.0
S : 0.14285714285714285
T : 0.0
W : 0.0
Y : 0.0
V : 0.14285714285714285
5 17
A : 0.0
R : 0.0
N : 0.0
D : 0.2857142857142857
C : 0.0
Q : 0.0
E : 0.0
G : 0.0
H : 0.0
I : 0

In [28]:
tempar = np.zeros((20,len(columns)))

In [29]:
tempar[:,1] = blosum62_background

In [67]:
result_hmmscan = subprocess.run(['wsl', 'hmmscan', '--tblout', './data/result.tbl', './data/Pfam/Pfam-A.hmm', './data/Pfam/AF-Q72KT1-F1.fasta'], stdout=subprocess.PIPE, text=True)

In [68]:
with open('./data/result.tbl', 'r') as f:
    lines = f.readlines()
    for line in lines:
        if line[0] != '#': 
            if float(line.split()[4]) < 0.01:
                family = line.split()[1].split('.')[0]
                print(family)
                break
                

PF00107


In [69]:
print(float('1.1e-18'))

1.1e-18


In [70]:
subprocess.run(['wsl', 'clustalo', '--p1', './data/Pfam/PF00107.alignment.full', '--p2', './data/Pfam/AF-Q72KT1-F1.fasta', '-o', './data/Pfam/output_alignment.fasta', '--threads=6'], stdout = subprocess.PIPE, text = True)

CompletedProcess(args=['wsl', 'clustalo', '--p1', './data/Pfam/PF00107.alignment.full', '--p2', './data/Pfam/AF-Q72KT1-F1.fasta', '-o', './data/Pfam/output_alignment.fasta', '--threads=6'], returncode=1, stdout='')

aa_prop_array = np.zeros((20,len(columns)))
for n_col, col in enumerate(columns):
    col_no_gaps = np.char.upper(np.array(list(alignment[:, col]))[np.array(list(alignment[:, col])) != '-'])
    aa_percs = np.array([len(col_no_gaps[col_no_gaps == aa])/len(col_no_gaps) for aa in aa_order])
    aa_prop_array[:, n_col] = aa_percs

In [71]:
alignment_array = np.array([list(rec.seq) for rec in alignment], dtype = 'U1')

In [72]:
type(columns[2])

numpy.int64

In [73]:
type(np.array([1,2,3])[0])

numpy.int64

In [74]:
alignment_array_filtered = alignment_array[:, columns.astype(int)]

In [75]:
alignment_array_filtered.shape

(150579, 363)

In [76]:
aa_prop_array2 = np.zeros((20, alignment_array_filtered.shape[1]))
for n_col, col in enumerate(alignment_array_filtered.T):
    col_no_gaps = np.char.upper(col[col != '-'])
    aa_percs = np.array([np.sum(col_no_gaps == aa)/len(col_no_gaps) for aa in aa_order])
    aa_prop_array2[:, n_col] = aa_percs

In [78]:
#print(np.sum(aa_prop_array[:,100]))

In [79]:
print(np.sum(aa_prop_array2[:,100]))

0.9999999999999999


In [80]:
blosum62_background

array([0.078, 0.051, 0.041, 0.052, 0.024, 0.034, 0.059, 0.083, 0.025,
       0.062, 0.092, 0.056, 0.024, 0.044, 0.043, 0.059, 0.055, 0.014,
       0.034, 0.072])

In [81]:
aa_prop_array2[:,100]

array([0.13379074, 0.0626072 , 0.02915952, 0.06689537, 0.00171527,
       0.03859348, 0.05231561, 0.08576329, 0.02487136, 0.04459691,
       0.07890223, 0.10120069, 0.01286449, 0.00686106, 0.06861063,
       0.08233276, 0.08233276, 0.00171527, 0.01286449, 0.01200686])

In [82]:
from scipy.special import rel_entr

In [83]:
p = aa_prop_array2[:,100]
q = blosum62_background
m = 0.5 * (p + q)
jsd = 0.5 * np.sum(rel_entr(p, m)) + 0.5 * np.sum(rel_entr(q, m))

In [84]:
def jsd(p, q):
    """
    This function calculates the Jensen-Shannon divergence between two probability distributions. p is observed, q is background distribution.
    """
    from scipy.special import rel_entr
    import numpy as np
    m = 0.5 * (p + q)
    jsd = 0.5 * np.sum(rel_entr(p, m)) + 0.5 * np.sum(rel_entr(q, m))
    return jsd

In [85]:
for col in aa_prop_array2.T:
    print(jsd(col, blosum62_background))

0.44373191881355406
0.4425456792302531
0.3667071160746605
0.3705128144086466
0.3459427672395744
0.37616502503443405
0.35662811526117566
0.32300380469661033
0.27925994543043114
0.3722537597643306
0.3120182872392672
0.2861033168862673
0.39349767166917643
0.27381501972149513
0.1803755514268914
0.21090253166833078
0.17804262157433348
0.2038192314476066
0.21235825791458762
0.1461776267001786
0.10112674879426214
0.17044851748904885
0.16575740821312113
0.0954447178543616
0.11504998057544759
0.08612424138088812
0.08248351483440174
0.06167121466574231
0.05595157798976824
0.014631709402310098
0.04513811001942901
0.028336721764746928
0.044509282050908885
0.027794664883851794
0.016991495024591897
0.03113197328033379
0.015386054746461503
0.017520435228563322
0.02592750661480845
0.018055019394899646
0.02007348397975172
0.021678104416894835
0.014425979455550984
0.011873537931196559
0.01583020097395737
0.015401336317666062
0.010946664737336995
0.013716882864131388
0.014733459366521432
0.01494452058555

In [1]:
from conservation import conservation_score

In [2]:
conservation_result = conservation_score(pdb = './data/Pfam/AF-Q72KT1-F1.pdb')

PF00107


In [10]:
print(np.sum(conservation_result > 0.4))

34


In [9]:
from Bio import AlignIO
import numpy as np
import time
import subprocess

In [5]:
start_time = time.time()
alignment = AlignIO.read('./data/Pfam/output_alignment.fasta', 'fasta')
alignment_array = np.array([list(rec.seq) for rec in alignment], dtype = 'U1')
end_time = time.time()
print(f'Elapsed time: {end_time - start_time}') #24.3 s

Elapsed time: 23.3802752494812


In [ ]:
start_time = time.time()
grep -v '^>' your_file.txt | awk 'BEGIN { ORS=""; } { if (NF == 0) { print "\n"; } else { print; } }' > combined_sequences.txt

subprocess.run(['wsl', 'grep', '-v', '"v"', './data/Pfam/output_alignment.fasta', '|', 'awk', './data/output_alignment.fasta', '--threads=1'], stdout = subprocess.PIPE, text = True)

In [21]:
print(result.stdout.split('\n')[0])

ATOM      1  N   MET A   1       7.413  -5.613 -26.430  1.00 95.44           N  


In [46]:
# coordinate extraction from pdb file
time1 = time.time()
with open('./data/Pfam/AF-Q72KT1-F1.pdb', 'r') as f:
    lines = [line for line in f if line.startswith('ATOM')]
coords = np.array([line.split()[6:9] for line in lines], dtype=float)
time2 = time.time()
print(f'Elapsed time: {time2 - time1}') #0.18 s

Elapsed time: 0.01209568977355957
